import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

export default [
  {
    // next-env.d.ts is generated by Next and rewritten on every build.
    ignores: [".next/**", "node_modules/**", "coverage/**", "fixtures/**", "next-env.d.ts"],
  },
  ...coreWebVitals,
  ...typescript,
  {
    // Config files legitimately export a literal.
    files: ["*.config.mjs", "*.config.ts"],
    rules: { "import/no-anonymous-default-export": "off" },
  },
  {
    rules: {
      // Unused code is deleted, not left behind (AGENTS.md #7).
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // `any` defeats the point of the domain model being typed.
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
];
