CREATE TYPE "public"."account_kind" AS ENUM('BANK_ACCOUNT', 'CREDIT_CARD');--> statement-breakpoint
CREATE TYPE "public"."period_source" AS ENUM('DECLARED', 'DERIVED');--> statement-breakpoint
ALTER TABLE "bank_accounts" ADD COLUMN "account_kind" "account_kind" DEFAULT 'BANK_ACCOUNT' NOT NULL;--> statement-breakpoint
ALTER TABLE "bank_statements" ADD COLUMN "identified_account_kind" "account_kind";--> statement-breakpoint
ALTER TABLE "bank_statements" ADD COLUMN "identified_currency" text;--> statement-breakpoint
ALTER TABLE "bank_statements" ADD COLUMN "period_source" "period_source";--> statement-breakpoint
-- Every period already in this table came from the old identification path, which accepted
-- a period only where the document declared one. DECLARED is therefore factually true of all
-- of them, and leaving them null would mean "unknown provenance" for rows whose provenance
-- we do know. Not generated by drizzle-kit: it describes data, not schema.
UPDATE "bank_statements" SET "period_source" = 'DECLARED'
 WHERE "period_start" IS NOT NULL AND "period_end" IS NOT NULL;
