/**
 * The Excel file, opened the way an accountant would open it.
 *
 * spec: docs/workflows/missing-invoice-report.md §5, §9 · docs/architecture.md §19
 * decision: docs/decisions/0017-reconciliation-export.md
 *
 * Every assertion reads the generated bytes back, so what is checked is the file, not the
 * rows handed to the writer.
 */

import ExcelJS from "exceljs";
import { inflateRawSync } from "node:zlib";
import { describe, expect, it } from "vitest";

import type { ExportRow } from "../../src/export/rows";
import {
  buildWorkbook,
  COLUMN_HEADERS,
  RECONCILIATION_SHEET,
  SUMMARY_SHEET,
  type WorkbookContext,
} from "../../src/export/workbook";
import type { Summary } from "../../src/report/summary";

const ORIGIN = "https://app.example.com";

const summary: Summary = {
  documentsRequired: 2,
  matched: 1,
  notFound: 1,
  needsReview: 0,
  waiting: 0,
  blocked: 0,
  notRequired: 0,
};

const context: WorkbookContext = {
  origin: ORIGIN,
  generatedAt: new Date("2026-09-26T10:00:00Z"),
  transactionsProcessed: 3,
  summary,
  run: {
    startedAt: new Date("2026-09-25T08:00:00Z"),
    coverageStart: "2026-03-01",
    coverageEnd: "2026-03-31",
  },
  accounts: ["HDFC Bank XXXX1234"],
};

function row(over: Partial<ExportRow> = {}): ExportRow {
  return {
    date: "2026-03-05",
    account: "HDFC Bank XXXX1234",
    description: "ADOBE SYSTEMS",
    direction: "Debit",
    amount: 1234.56,
    currency: "INR",
    vendor: "Adobe",
    documentNeeded: "Yes",
    status: "Matched",
    howResolved: "Retrieved from email",
    reason: "A software subscription.",
    document: { id: "5f1c3a8e-0000-4000-8000-000000000001", filename: "adobe-march.pdf" },
    ...over,
  };
}

async function open(bytes: Buffer) {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(bytes as unknown as ArrayBuffer);
  return workbook;
}

/** Every XML part of the file, inflated, so a string search sees what Excel would. */
function everyPart(bytes: Buffer): string {
  const parts: string[] = [];
  let offset = 0;
  // Local file headers: a zip is a sequence of them. Enough of the format to read an xlsx.
  while (bytes.readUInt32LE(offset) === 0x04034b50) {
    const method = bytes.readUInt16LE(offset + 8);
    const compressed = bytes.readUInt32LE(offset + 18);
    const nameLength = bytes.readUInt16LE(offset + 26);
    const extraLength = bytes.readUInt16LE(offset + 28);
    const start = offset + 30 + nameLength + extraLength;
    const data = bytes.subarray(start, start + compressed);
    parts.push((method === 8 ? inflateRawSync(data) : data).toString("utf8"));
    offset = start + compressed;
  }
  // A search over some of the parts proves nothing about the rest. The end-of-central-
  // directory record says how many entries there are; read them all or fail loudly.
  const end = bytes.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
  expect(parts.length).toBe(bytes.readUInt16LE(end + 10));
  return parts.join("\n");
}

describe("the reconciliation sheet", () => {
  it("has §9's columns, in order", async () => {
    const sheet = (await open(await buildWorkbook([row()], context))).getWorksheet(
      RECONCILIATION_SHEET,
    )!;

    expect((sheet.getRow(1).values as unknown[]).slice(1)).toEqual(COLUMN_HEADERS);
    expect(COLUMN_HEADERS).toEqual([
      "Date",
      "Account",
      "Description",
      "Direction",
      "Amount",
      "Currency",
      "Vendor",
      "Document needed",
      "Status",
      "How resolved",
      "Reason",
      "Document",
    ]);
  });

  it("writes dates as dates and amounts as numbers an accountant can sum", async () => {
    const sheet = (await open(await buildWorkbook([row()], context))).getWorksheet(
      RECONCILIATION_SHEET,
    )!;
    const cells = sheet.getRow(2);

    expect(cells.getCell(1).value).toEqual(new Date(Date.UTC(2026, 2, 5)));
    expect(cells.getCell(5).value).toBe(1234.56);
    expect(cells.getCell(8).value).toBe("Yes");
    expect(cells.getCell(9).value).toBe("Matched");
  });

  it("links a document to its page in the application", async () => {
    const sheet = (await open(await buildWorkbook([row()], context))).getWorksheet(
      RECONCILIATION_SHEET,
    )!;

    expect(sheet.getRow(2).getCell(12).value).toEqual({
      text: "adobe-march.pdf",
      hyperlink: `${ORIGIN}/documents/5f1c3a8e-0000-4000-8000-000000000001`,
    });
  });

  it("writes no link at all for a row with no document", async () => {
    const sheet = (
      await open(
        await buildWorkbook(
          [row({ document: null, status: "Not found", howResolved: null })],
          context,
        ),
      )
    ).getWorksheet(RECONCILIATION_SHEET)!;

    const cell = sheet.getRow(2).getCell(12);
    expect(cell.value).toBeNull();
    expect(cell.hyperlink).toBeUndefined();
  });

  it("carries no storage location anywhere in the file", async () => {
    const xml = everyPart(await buildWorkbook([row()], context));

    // The one link in the file is the application's.
    expect(xml).toContain(`${ORIGIN}/documents/5f1c3a8e-0000-4000-8000-000000000001`);
    expect(xml).not.toMatch(/blob\.vercel-storage\.com/);
    expect(xml).not.toMatch(/workspaces\/[^"<]*\/documents\//);
  });

  it("is a valid file with only its headers when there are no transactions", async () => {
    const workbook = await open(
      await buildWorkbook([], {
        ...context,
        transactionsProcessed: 0,
        summary: { ...summary, documentsRequired: 0, matched: 0, notFound: 0 },
      }),
    );

    const sheet = workbook.getWorksheet(RECONCILIATION_SHEET)!;
    expect(sheet.rowCount).toBe(1);
    expect((sheet.getRow(1).values as unknown[]).slice(1)).toEqual(COLUMN_HEADERS);
  });
});

describe("the summary sheet", () => {
  it("repeats the report's summary, so the file can be checked against itself", async () => {
    const sheet = (await open(await buildWorkbook([row()], context))).getWorksheet(SUMMARY_SHEET)!;

    const lines = new Map<string, unknown>();
    sheet.eachRow((line) => lines.set(String(line.getCell(1).value), line.getCell(2).value));

    expect(lines.get("Transactions processed")).toBe(3);
    expect(lines.get("Needed a document")).toBe(2);
    expect(lines.get("Matched")).toBe(1);
    expect(lines.get("Not found")).toBe(1);
    expect(lines.get("Marked as needing no document")).toBe(0);
    expect(lines.get("Generated (UTC)")).toEqual(context.generatedAt);
    expect(lines.get("Coverage")).toBe("2026-03-01 → 2026-03-31");
    expect(lines.get("Accounts")).toBe("HDFC Bank XXXX1234");
  });

  it("says nothing about a run when there has not been one", async () => {
    const sheet = (await open(await buildWorkbook([], { ...context, run: null }))).getWorksheet(
      SUMMARY_SHEET,
    )!;

    const labels: string[] = [];
    sheet.eachRow((line) => labels.push(String(line.getCell(1).value)));
    expect(labels).not.toContain("Last run (UTC)");
    expect(labels).not.toContain("Coverage");
  });
});
