/**
 * Database schema.
 *
 * Implements docs/domain-model.md. Names follow docs/glossary.md; states follow
 * docs/state-machines.md. If you need a concept that is not here, add it to the domain
 * model first.
 *
 * Two rules run through the whole file:
 *
 * 1. Every workspace-scoped table carries `workspaceId`. Isolation is enforced in the
 *    application layer (docs/architecture.md §5.2), so the column has to be present for
 *    the data access layer to filter on.
 * 2. Domain invariants are database constraints, not conventions (docs/architecture.md
 *    §2.6). Where a rule can be an index, it is one.
 *
 * Money is stored as integer minor units (paise, cents) with an explicit currency, never
 * as a float. The balance equation adds thousands of these together and must be exact.
 */

import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";

/* ------------------------------------------------------------------ enums */
/* Values come from docs/state-machines.md. Do not add one without adding it there. */

export const statementStateEnum = pgEnum("statement_state", [
  "UPLOADING",
  "IDENTIFYING",
  "NEEDS_ACCOUNT",
  "PARSING",
  "VALIDATING",
  "COMPLETED",
  "FAILED",
]);

export const validationOutcomeEnum = pgEnum("validation_outcome", ["VALID", "DISCREPANCY"]);

export const accountKindEnum = pgEnum("account_kind", ["BANK_ACCOUNT", "CREDIT_CARD"]);

export const periodSourceEnum = pgEnum("period_source", ["DECLARED", "DERIVED"]);

export const requirementStateEnum = pgEnum("requirement_state", [
  "IDENTIFIED",
  "SEARCHING",
  "EVALUATING",
  "NEEDS_REVIEW",
  "NOT_FOUND",
  "RESOLVED",
  "BLOCKED",
  "FAILED",
]);

export const resolutionMethodEnum = pgEnum("resolution_method", [
  "AUTO_RETRIEVED",
  "AUTO_MATCHED",
  "USER_CONFIRMED",
  "USER_LINKED",
  "NOT_REQUIRED",
]);

export const documentStateEnum = pgEnum("document_state", [
  "STORED",
  "EXTRACTING",
  "CLASSIFYING",
  "EXTRACTED",
  "UNREADABLE",
  "NOT_AN_INVOICE",
]);

/** Three-valued on purpose: uncertainty is not a negative. docs/state-machines.md §3. */
export const classificationEnum = pgEnum("classification", [
  "IS_INVOICE",
  "UNCERTAIN",
  "IS_NOT_INVOICE",
]);

export const documentSourceEnum = pgEnum("document_source", ["GMAIL", "MANUAL_UPLOAD"]);

export const runStateEnum = pgEnum("run_state", ["RUNNING", "COMPLETED", "FAILED"]);

export const directionEnum = pgEnum("direction", ["DEBIT", "CREDIT"]);

export const gmailConnectionStateEnum = pgEnum("gmail_connection_state", [
  "CONNECTED",
  "NEEDS_REAUTH",
  "DISCONNECTED",
]);

/* ------------------------------------------------------------------ identity */

/**
 * The authenticated user, and the table the Auth.js Drizzle adapter owns
 * (docs/decisions/0006-authentication.md).
 *
 * `id` is opaque and generated by the adapter. It is deliberately NOT the Google `sub`
 * claim — that lives one table over, in `accounts.providerAccountId`. What `0004` asked
 * for is that this schema stand alone rather than reference a provider-owned table, and
 * it does: these are our tables, in our migrations, so tests still run against a bare
 * Postgres with no auth schema present.
 *
 * `text` rather than `uuid` because the column holds whatever the auth provider's adapter
 * generates, which is not guaranteed to be a UUID.
 */
export const users = pgTable("users", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  email: text("email").notNull().unique(),
  // Null until the provider asserts it. Google always does; the column is nullable
  // because the adapter's user shape requires it to be.
  emailVerified: timestamp("email_verified", { withTimezone: true }),
  name: text("name"),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/* ---------------------------------------------------------- auth.js infrastructure */

/*
 * The three tables below are Auth.js's, not the domain's. They are session and identity
 * plumbing, they belong to a user rather than to a workspace, and they must never be
 * added to `workspaceScopedTables` — see docs/decisions/0006-authentication.md and the
 * test that asserts their absence.
 */

/**
 * The external identity behind a user. `providerAccountId` is the Google `sub`.
 *
 * Holds the sign-in grant only, whose scopes are profile and email. The Gmail grant does
 * **not** live here: it belongs to a workspace rather than a user, and is stored encrypted
 * in `gmail_connections` below (docs/decisions/0006-authentication.md, amended).
 */
export const accounts = pgTable(
  "accounts",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (t) => [
    primaryKey({ columns: [t.provider, t.providerAccountId] }),
    index("accounts_user_idx").on(t.userId),
  ],
);

/** Server-side sessions. ADR 0006 chooses database sessions over a JWT. */
export const sessions = pgTable(
  "sessions",
  {
    sessionToken: text("session_token").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expires: timestamp("expires", { withTimezone: true }).notNull(),
  },
  (t) => [index("sessions_user_idx").on(t.userId)],
);

/**
 * Required by the adapter's interface. Unused with Google as the only provider — there is
 * no email link and no passwordless flow in V1.
 */
export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { withTimezone: true }).notNull(),
  },
  (t) => [primaryKey({ columns: [t.identifier, t.token] })],
);

/* ------------------------------------------------------------------ workspace */

/** The authorization boundary. Everything below belongs to exactly one of these. */
export const workspaces = pgTable(
  "workspaces",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ownerId: text("owner_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("workspaces_owner_idx").on(t.ownerId)],
);

/* ------------------------------------------------------------------ accounts and statements */

export const bankAccounts = pgTable(
  "bank_accounts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    bankName: text("bank_name").notNull(),
    /** As printed on the statement — often masked. Identity is scoped to the workspace. */
    accountIdentifier: text("account_identifier").notNull(),
    accountType: text("account_type"),
    /** A credit card is an account here too. `docs/decisions/0008` says why. */
    accountKind: accountKindEnum("account_kind").notNull().default("BANK_ACCOUNT"),
    /**
     * ISO 4217, validated against `src/money/currencies.ts` before it is written.
     *
     * Deliberately `text` rather than an enum: adding a currency should be a code change
     * with a test, not a migration. Set once, when the account is created, and never
     * rewritten — canonical transactions carry their own currency, so changing this later
     * would re-denominate movements already recorded against the account (Step 3a).
     */
    currency: text("currency").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // The lookup in upload-statement Step 3a never crosses a workspace, so neither does
    // this uniqueness.
    //
    // `accountKind` is deliberately NOT part of this. Two accounts are the same account
    // because they share a workspace, a bank and an identifier; including the kind would let
    // one account exist twice under two kinds, and since canonical transactions are keyed on
    // `bankAccountId`, a split account silently defeats deduplication — the one failure
    // Step 5a names as destroying a real payment.
    //
    // Matched case-insensitively, which is not fussiness. A model reading the same Axis
    // statement twice returned "AXIS BANK" once and "Axis Bank" the next time, and a
    // case-sensitive index made those two accounts for one real account — the same split,
    // arrived at by a different route. Case is how a statement is typeset, never which
    // account it is. `src/statements/account-identity.ts` holds the matching rule; it must
    // agree with this index exactly, and `tests/db/invariants.test.ts` pins that.
    uniqueIndex("bank_accounts_identity_idx").on(
      t.workspaceId,
      sql`lower(${t.bankName})`,
      sql`upper(${t.accountIdentifier})`,
    ),
  ],
);

/**
 * One uploaded file.
 *
 * `periodStart`/`periodEnd` are nullable only because they are unknown until the file is
 * identified; a statement cannot reach COMPLETED without them (upload-statement Step 3),
 * since Statement Coverage is derived from these columns.
 */
export const bankStatements = pgTable(
  "bank_statements",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    /** Null until Step 3a binds the statement to an account. */
    bankAccountId: uuid("bank_account_id").references(() => bankAccounts.id, {
      onDelete: "restrict",
    }),
    /**
     * The files of one upload, so a batch can be shown together.
     *
     * upload-statement §11: a batch is a presentation grouping and nothing more — the
     * files within it are processed independently and may reach different outcomes, so
     * nothing keyed on this column may make one file's fate depend on another's.
     */
    uploadBatchId: uuid("upload_batch_id").notNull(),
    filename: text("filename").notNull(),
    mimeType: text("mime_type").notNull(),
    storageRef: text("storage_ref").notNull(),
    state: statementStateEnum("state").notNull().default("UPLOADING"),
    /*
     * What identification read off the document, as printed.
     *
     * Separate from the bound `bankAccountId` on purpose. A statement in NEEDS_ACCOUNT
     * has these and no binding, and that is what the account picker shows the user; a
     * bound statement keeps them so a wrong binding can be traced back to what the
     * document actually said rather than to what we decided it meant.
     */
    identifiedBankName: text("identified_bank_name"),
    identifiedAccountIdentifier: text("identified_account_identifier"),
    identifiedAccountType: text("identified_account_type"),
    identifiedAccountKind: accountKindEnum("identified_account_kind"),
    /**
     * The currency code the document gave, raw — including one we do not support.
     *
     * Kept unvalidated on purpose. A statement in NEEDS_ACCOUNT because its currency was
     * unrecognised is only debuggable if what the model actually said survives; validating
     * on the way in would discard the one piece of evidence worth having.
     */
    identifiedCurrency: text("identified_currency"),
    validationOutcome: validationOutcomeEnum("validation_outcome"),
    failureReason: text("failure_reason"),
    periodStart: date("period_start"),
    periodEnd: date("period_end"),
    /** Null exactly when the period is. `docs/decisions/0008`. */
    periodSource: periodSourceEnum("period_source"),
    openingBalance: bigint("opening_balance", { mode: "bigint" }),
    closingBalance: bigint("closing_balance", { mode: "bigint" }),
    totalCredits: bigint("total_credits", { mode: "bigint" }),
    totalDebits: bigint("total_debits", { mode: "bigint" }),
    lineCount: integer("line_count"),
    /** The column mapping a model inferred, kept for debugging a bad parse. ADR 0003. */
    columnMapping: jsonb("column_mapping"),
    /**
     * A digest of the bytes, so the same document is recognisable as the same document.
     *
     * Its job is to keep canonical identity stable. The mapping is a model's answer and the
     * model does not always give the same one: two uploads of one ICICI statement chose
     * different description columns, 16% of the rows came out with different descriptions,
     * and since `description_normalized` is part of
     * `canonical_transactions_identity_idx` the second upload created 212 transactions that
     * already existed. Re-uploading a file now reuses the mapping already derived for those
     * exact bytes, so the descriptions are identical and deduplication holds.
     *
     * Not unique: the same statement may legitimately be uploaded twice, and that is the
     * case this exists to make safe.
     */
    contentHash: text("content_hash"),
    uploadedAt: timestamp("uploaded_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("bank_statements_workspace_idx").on(t.workspaceId),
    index("bank_statements_batch_idx").on(t.workspaceId, t.uploadBatchId),
    index("bank_statements_coverage_idx").on(t.bankAccountId, t.periodStart, t.periodEnd),
    // The lookup that reuses a mapping: this workspace's earlier copy of these exact bytes.
    index("bank_statements_content_idx").on(t.workspaceId, t.contentHash),
  ],
);

/**
 * One row exactly as extracted from one statement. Immutable evidence.
 *
 * Overlapping statements produce two of these for one payment; both point at the same
 * canonical transaction.
 */
export const statementLines = pgTable(
  "statement_lines",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    statementId: uuid("statement_id")
      .notNull()
      .references(() => bankStatements.id, { onDelete: "cascade" }),
    rowIndex: integer("row_index").notNull(),
    valueDate: date("value_date").notNull(),
    description: text("description").notNull(),
    amountMinor: bigint("amount_minor", { mode: "bigint" }).notNull(),
    direction: directionEnum("direction").notNull(),
    balanceMinor: bigint("balance_minor", { mode: "bigint" }),
    /**
     * The bank's own reference for this row — a UTR, a cheque number — as printed.
     *
     * Deliberately NOT unique here, unlike its counterpart on `canonical_transactions`.
     * Two overlapping statements both printing one UTR produce two of these rows and one
     * canonical transaction, which is the whole point of this table being evidence rather
     * than identity.
     *
     * It has to live on the line as well as on the transaction. Promotion runs in a
     * background workflow that may run twice, and it recovers by re-reading these rows —
     * so a reference held only in memory would be lost on a retry, and Step 5a's rule that
     * a reference decides identity on its own would silently stop applying to exactly the
     * statements that had already failed once.
     */
    externalReference: text("external_reference"),
    canonicalTransactionId: uuid("canonical_transaction_id").references(
      () => canonicalTransactions.id,
      { onDelete: "set null" },
    ),
  },
  (t) => [
    uniqueIndex("statement_lines_row_idx").on(t.statementId, t.rowIndex),
    index("statement_lines_canonical_idx").on(t.canonicalTransactionId),
  ],
);

/**
 * The business's single record of one financial movement.
 *
 * Everything downstream references this, never a statement line.
 */
export const canonicalTransactions = pgTable(
  "canonical_transactions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    bankAccountId: uuid("bank_account_id")
      .notNull()
      .references(() => bankAccounts.id, { onDelete: "cascade" }),
    valueDate: date("value_date").notNull(),
    /** Always positive; `direction` carries the sign. */
    amountMinor: bigint("amount_minor", { mode: "bigint" }).notNull(),
    direction: directionEnum("direction").notNull(),
    currency: text("currency").notNull(),
    description: text("description").notNull(),
    /** Case, whitespace and punctuation normalized. Formatting only — never interpreted. */
    descriptionNormalized: text("description_normalized").notNull(),
    /**
     * Distinguishes two legitimately identical payments on one day from the same payment
     * seen in two overlapping statements. upload-statement Step 5a.
     */
    occurrenceIndex: integer("occurrence_index").notNull().default(0),
    /** A bank-supplied reference or UTR. When present it alone establishes identity. */
    externalReference: text("external_reference"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // The dedup rule, as a constraint. A second upload of the same statement collides
    // here rather than silently creating duplicate transactions.
    uniqueIndex("canonical_transactions_identity_idx").on(
      t.bankAccountId,
      t.valueDate,
      t.amountMinor,
      t.direction,
      t.descriptionNormalized,
      t.occurrenceIndex,
    ),
    // When the bank gives a reference, it wins outright.
    uniqueIndex("canonical_transactions_reference_idx")
      .on(t.bankAccountId, t.externalReference)
      .where(sql`external_reference is not null`),
    index("canonical_transactions_workspace_date_idx").on(t.workspaceId, t.valueDate),
  ],
);

/* ------------------------------------------------------------------ vendors */

export const vendors = pgTable(
  "vendors",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    legalName: text("legal_name"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("vendors_workspace_idx").on(t.workspaceId)],
);

/**
 * An alternate representation of a vendor.
 *
 * `confirmed` is the line between a user's decision and a model's guess: only a confirmed
 * alias is Business Knowledge (docs/architecture.md §11). Inferred aliases may widen a
 * search within the run that produced them and are not persisted as fact.
 */
export const vendorAliases = pgTable(
  "vendor_aliases",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    vendorId: uuid("vendor_id")
      .notNull()
      .references(() => vendors.id, { onDelete: "cascade" }),
    alias: text("alias").notNull(),
    aliasNormalized: text("alias_normalized").notNull(),
    confirmed: boolean("confirmed").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("vendor_aliases_identity_idx").on(t.workspaceId, t.aliasNormalized)],
);

/* ------------------------------------------------------------------ documents and invoices */

/**
 * Any file offered as evidence — invoice, receipt, payment confirmation.
 *
 * Every file is one of these first. Only some become invoices (docs/domain-model.md §5.1).
 */
export const supportingDocuments = pgTable(
  "supporting_documents",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    storageRef: text("storage_ref").notNull(),
    filename: text("filename").notNull(),
    mimeType: text("mime_type").notNull(),
    source: documentSourceEnum("source").notNull(),
    state: documentStateEnum("state").notNull().default("STORED"),
    classification: classificationEnum("classification"),
    /** Provenance for a retrieved document: account, message, attachment. */
    sourceMetadata: jsonb("source_metadata"),
    /** Set when the document resolves a requirement without being classified an invoice. */
    canonicalTransactionId: uuid("canonical_transaction_id").references(
      () => canonicalTransactions.id,
      { onDelete: "set null" },
    ),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("supporting_documents_workspace_idx").on(t.workspaceId),
    index("supporting_documents_transaction_idx").on(t.canonicalTransactionId),
  ],
);

/**
 * A document classified and extracted as a charge from a vendor.
 *
 * The 1:1 rule with transactions is enforced below, and constrains extracted invoices
 * only — a transaction may hold several supporting documents but at most one invoice.
 */
export const invoices = pgTable(
  "invoices",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    vendorId: uuid("vendor_id").references(() => vendors.id, { onDelete: "set null" }),
    invoiceNumber: text("invoice_number"),
    invoiceDate: date("invoice_date"),
    totalMinor: bigint("total_minor", { mode: "bigint" }),
    currency: text("currency"),
    taxMinor: bigint("tax_minor", { mode: "bigint" }),
    subtotalMinor: bigint("subtotal_minor", { mode: "bigint" }),
    /** Domain invariant 8: an invoice links to at most one transaction. */
    canonicalTransactionId: uuid("canonical_transaction_id").references(
      () => canonicalTransactions.id,
      { onDelete: "set null" },
    ),
    /**
     * The invoice this one may be a second copy of. docs/glossary.md, Suspected Duplicate.
     *
     * Points at the older invoice, never the other way round, so a third copy of the same
     * document points at the same original rather than forming a chain nobody can read.
     *
     * `set null` rather than `cascade`: if the original is deleted this invoice is no
     * longer a duplicate of anything, and it is still a real invoice built from a real
     * document. Deleting the thing it resembled must not delete it.
     */
    suspectedDuplicateOfInvoiceId: uuid("suspected_duplicate_of_invoice_id").references(
      (): AnyPgColumn => invoices.id,
      { onDelete: "set null" },
    ),
    /** Which fields agreed, in the user's language. Shown beside both documents. */
    duplicateReason: text("duplicate_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // Domain invariant 9: a transaction has at most one invoice. Partial, because many
    // invoices are legitimately unlinked and NULLs must not collide.
    uniqueIndex("invoices_transaction_idx")
      .on(t.canonicalTransactionId)
      .where(sql`canonical_transaction_id is not null`),
    index("invoices_workspace_idx").on(t.workspaceId),
    // The review queue asks for the flagged ones only, and they are the rare case.
    index("invoices_duplicate_idx")
      .on(t.workspaceId, t.suspectedDuplicateOfInvoiceId)
      .where(sql`suspected_duplicate_of_invoice_id is not null`),
  ],
);

/**
 * A transaction the system proposes as the possible subject of an invoice.
 *
 * spec: docs/workflows/manual-invoice-upload.md §8, §9 · decision:
 * docs/decisions/0011-matching-is-evidence-not-score.md
 *
 * A proposal, not a decision. The link itself lives on `invoices.canonicalTransactionId`
 * and is constrained there; these rows are the working-out, kept so that the screen which
 * asks the user can show what the system saw rather than a number
 * (`docs/workflows/invoice-match-review.md §5`).
 *
 * `evidence` is persisted rather than recomputed because feature H renders it minutes or
 * days after the decision, and recomputing would mean H deriving candidates a second time.
 * Two implementations of the same reasoning drift, and the one the user is shown would be
 * the one nothing tested.
 *
 * `modelVerdict` is `text` and not an enum on purpose. It is a transcript of one model
 * call, not a state anything moves through, and `docs/state-machines.md` should stay the
 * list of things that are.
 *
 * Deliberately not shared with Gmail retrieval's future candidates. Those propose a
 * document for a requirement; these propose a transaction for an invoice. One table for
 * both needs a `kind` column and two nullable foreign-key pairs, and every query then
 * carries a filter the type system cannot enforce -- the single missing filter
 * `workspace-scope.ts` exists to make impossible.
 */
export const invoiceMatchCandidates = pgTable(
  "invoice_match_candidates",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    invoiceId: uuid("invoice_id")
      .notNull()
      .references(() => invoices.id, { onDelete: "cascade" }),
    canonicalTransactionId: uuid("canonical_transaction_id")
      .notNull()
      .references(() => canonicalTransactions.id, { onDelete: "cascade" }),
    /** Deterministic rank, 0 best. The order the user is shown them in. */
    rank: integer("rank").notNull(),
    /** The observable facts that put this transaction here. Never a score. */
    evidence: jsonb("evidence").notNull(),
    /** SAME | UNSURE | DIFFERENT, or null where the model was never asked. */
    modelVerdict: text("model_verdict"),
    modelReason: text("model_reason"),
    /** The bounded read hit its cap, so this set is not everything that could have matched. */
    truncated: boolean("truncated").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // One proposal per pair. A re-run replaces the set; it must not double it.
    uniqueIndex("invoice_match_candidates_identity_idx").on(t.invoiceId, t.canonicalTransactionId),
    // Matching's own direction: what did we propose for this invoice.
    index("invoice_match_candidates_invoice_idx").on(t.workspaceId, t.invoiceId),
    /*
     * Review's direction: what was proposed for this payment.
     *
     * Match review enters by requirement -- a transaction -- and asks which documents
     * named it. The unique index above leads with `invoice_id`, so it cannot answer that
     * without a scan, and the review screen is the one place in the product a person is
     * waiting on the answer.
     */
    index("invoice_match_candidates_transaction_idx").on(t.workspaceId, t.canonicalTransactionId),
  ],
);

/**
 * An invoice may be represented by several files.
 *
 * Carries `workspaceId` although both of its foreign keys already reach one, for the same
 * reason `vendor_aliases` does: `docs/architecture.md §5.2` enforces isolation in
 * application code, and `workspace-scope.ts` only guards a table it can filter. Without the
 * column this join would be the one table written outside the scope object, which is
 * exactly the single missing filter the design exists to make impossible.
 */
export const invoiceDocuments = pgTable(
  "invoice_documents",
  {
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    invoiceId: uuid("invoice_id")
      .notNull()
      .references(() => invoices.id, { onDelete: "cascade" }),
    documentId: uuid("document_id")
      .notNull()
      .references(() => supportingDocuments.id, { onDelete: "cascade" }),
    isPrimary: boolean("is_primary").notNull().default(false),
  },
  (t) => [
    uniqueIndex("invoice_documents_pk").on(t.invoiceId, t.documentId),
    index("invoice_documents_workspace_idx").on(t.workspaceId),
  ],
);

/* ------------------------------------------------------------------ reconciliation */

/**
 * The determination that a transaction should have a supporting document.
 *
 * Persisted, not derived: retrieval works against it and must be resumable, and the user
 * acts on it. docs/domain-model.md §3.12.
 */
export const invoiceRequirements = pgTable(
  "invoice_requirements",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    canonicalTransactionId: uuid("canonical_transaction_id")
      .notNull()
      .references(() => canonicalTransactions.id, { onDelete: "cascade" }),
    state: requirementStateEnum("state").notNull().default("IDENTIFIED"),
    /**
     * The run that identified this requirement.
     *
     * `set null` rather than `cascade`: a run is a record of work performed and is not a
     * source of truth about the requirement's state (docs/domain-model.md §3.13). Deleting
     * the history must never delete the work.
     */
    reconciliationRunId: uuid("reconciliation_run_id").references(() => reconciliationRuns.id, {
      onDelete: "set null",
    }),
    /** Why a document is believed to be required, in the user's language. */
    reason: text("reason"),
    /**
     * Who the payment looks like it went to, as identification read it.
     *
     * Text rather than a `vendors` FK on purpose. At this point the name is an unconfirmed
     * inference, and `vendorAliases.confirmed` above draws the line this respects: a guess
     * may inform the work of the run that produced it, but it is not persisted as fact. A
     * real vendor record is created later, from a decision the user confirmed.
     */
    vendorGuess: text("vendor_guess"),
    /** What the payment appears to be, in the business's terms. identifying-invoices §13. */
    businessContext: text("business_context"),
    resolutionMethod: resolutionMethodEnum("resolution_method"),
    resolvedDocumentId: uuid("resolved_document_id").references(() => supportingDocuments.id, {
      onDelete: "set null",
    }),
    /** Candidates the user rejected, so a later run does not offer them again. */
    rejectedDocumentIds: jsonb("rejected_document_ids").notNull().default([]),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // At most one requirement per transaction (docs/domain-model.md invariant 16).
    uniqueIndex("invoice_requirements_transaction_idx").on(t.canonicalTransactionId),
    index("invoice_requirements_queue_idx").on(t.workspaceId, t.state),
  ],
);

export const reconciliationRuns = pgTable(
  "reconciliation_runs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    state: runStateEnum("state").notNull().default("RUNNING"),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    coverageStart: date("coverage_start"),
    coverageEnd: date("coverage_end"),
    transactionsProcessed: integer("transactions_processed"),
    documentsRequired: integer("documents_required"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("reconciliation_runs_workspace_idx").on(t.workspaceId, t.startedAt)],
);

/* ------------------------------------------------------------------ knowledge */

/**
 * Durable fact learned from a user's confirmed decision. Never written from an
 * unconfirmed inference (docs/domain-model.md §3.14).
 */
export const businessKnowledge = pgTable(
  "business_knowledge",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    key: text("key").notNull(),
    value: jsonb("value").notNull(),
    confirmedAt: timestamp("confirmed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("business_knowledge_identity_idx").on(t.workspaceId, t.kind, t.key)],
);

/**
 * Persisted because the user may be away when it is raised and must be able to answer
 * later. The run does not stall waiting (docs/architecture.md §12C).
 */
export const clarificationQuestions = pgTable(
  "clarification_questions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    canonicalTransactionId: uuid("canonical_transaction_id").references(
      () => canonicalTransactions.id,
      { onDelete: "cascade" },
    ),
    /** The run that raised it. `set null` for the reason given on the requirement. */
    reconciliationRunId: uuid("reconciliation_run_id").references(() => reconciliationRuns.id, {
      onDelete: "set null",
    }),
    question: text("question").notNull(),
    /**
     * Who the payment looked like it went to, when the question was raised.
     *
     * Here rather than derived from the transaction afterwards because the answer has to
     * generalize to be worth keeping (`docs/domain-model.md §3.14`), and what it
     * generalizes over is the payee. A narration cannot stand in: `UPI/XYZ/9922/ORDER`
     * carries a reference number, so keying what we learn on it would teach us something
     * true of exactly one payment.
     */
    vendorGuess: text("vendor_guess"),
    options: jsonb("options"),
    answer: text("answer"),
    answeredAt: timestamp("answered_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("clarification_questions_open_idx").on(t.workspaceId, t.answeredAt)],
);

/* ------------------------------------------------------------------ mail */

/**
 * One Google account a workspace has authorized us to read mail from.
 *
 * spec: docs/workflows/connect-gmail.md · states: docs/state-machines.md §6
 *
 * Keyed within the workspace by the Google `sub` rather than the address, because an
 * address can change and a `sub` cannot. The same Google account connected to two
 * workspaces is two rows with two ciphertexts (`connect-gmail.md §4`); nothing here is
 * shared across workspaces.
 *
 * A row is never deleted by the application. Disconnecting nulls the credentials and
 * leaves the row in `DISCONNECTED`, so documents retrieved through it keep a provenance that
 * resolves, and connecting the same account again restores this row rather than adding a
 * second -- the unique index makes that the only possible outcome.
 *
 * Only the refresh token is stored, and only encrypted (`src/gmail/crypto.ts`). Access
 * tokens are minted from it when needed and never persisted: one long-lived secret at rest
 * rather than two.
 */
export const gmailConnections = pgTable(
  "gmail_connections",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    /** The Google `sub` claim of the account that was granted. */
    googleSubject: text("google_subject").notNull(),
    /** For display. Not an identity; see `googleSubject`. */
    email: text("email").notNull(),
    state: gmailConnectionStateEnum("state").notNull(),
    /** As Google reported them on the last grant (`connect-gmail.md §11`). */
    grantedScopes: text("granted_scopes").notNull(),
    /** Null exactly when `DISCONNECTED`; see the check below. */
    encryptedRefreshToken: text("encrypted_refresh_token"),
    connectedAt: timestamp("connected_at", { withTimezone: true }).notNull(),
    /** When retrieval last used this connection successfully. Written by feature K. */
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    disconnectedAt: timestamp("disconnected_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("gmail_connections_identity_idx").on(t.workspaceId, t.googleSubject),
    index("gmail_connections_workspace_state_idx").on(t.workspaceId, t.state),
    /*
     * Credentials exist exactly when the connection is not DISCONNECTED.
     *
     * "Disconnecting deletes the stored credentials" (connect-gmail.md §6) is then a
     * property of the table rather than of the code path that disconnects: no write can
     * leave a disconnected row holding a token, or a live one without.
     */
    check(
      "gmail_connections_credentials_check",
      sql`(${t.state} = 'DISCONNECTED') = (${t.encryptedRefreshToken} IS NULL)`,
    ),
  ],
);
